feature/semak
chillhaze/c0de_w13ards pull request #11
Opened 2021-03-31 20:48 UTC by OleksandrSemak

Add basic layout and fix body tag

2021-03-31 22:09 UTC, chillhaze requested changes

2021-03-31 22:09 UTC, chillhaze commented on src/sass/_semak-section.scss
> +.section--semak {
у нас нет класса section, чтобы задавать ему модификатор через "--". посмотри на примеры ребят и их названия

2021-03-31 22:09 UTC, chillhaze commented on src/index.html
> +    <include src="./partials/semak-section.html"></include>
здесь есть конфликт, либо ошибка, либо не последняя версия документа.

2021-04-01 06:56 UTC, OleksandrSemak commented on src/sass/_semak-section.scss
> +.section--semak {
Спасибо. У ребят у каждого по-своему, трудно выбрать один из них. Но поменял 'section' на 'welcome'

2021-04-01 07:05 UTC, OleksandrSemak commented on src/index.html
> +    <include src="./partials/semak-section.html"></include>
Конфликта у меня не было (по крайней мере программа об этом не уведомляла), версия 100% последняя. Да, в последней версии была ошибка - тег body дважды закрывался (один раз перед скриптом, второй - после скрипта). Я пофиксил повторение - оставил то, что после скрипта.

2021-04-01 07:15 UTC, chillhaze approved these changes

2021-04-01 07:16 UTC, merged